/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Marca_Auto;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pantera_negra.ConnectionManager;

/**
 *
 * @author carri
 */
public class Ventana extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana.class.getName());

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblMarcaAuto = new javax.swing.JLabel();
        txtMarca_Auto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTrabajador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnSeleccion = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setText("Bienvendos a Las Configuraciones");

        lblMarcaAuto.setText("Marca de Auto");

        txtMarca_Auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarca_AutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Costo del Servicio");

        jLabel4.setText("Nombre_Trabajador");

        jLabel5.setText("Nombre_Cliente");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSeleccion.setText("Seleccion");
        btnSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMarcaAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate))
                    .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarca_Auto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarcaAuto)
                    .addComponent(txtMarca_Auto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnSeleccion)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarca_AutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarca_AutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarca_AutoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
  ConnectionManager con = new ConnectionManager();

    String sql = "INSERT INTO configuraciones "
               + "(Marca_de_Auto, Costo_de_Servicio, Nombre_Trabajador, Nombre_Cliente) "
               + "VALUES (?, ?, ?, ?)";

    String marca = txtMarca_Auto.getText();
    String costo = txtServicio.getText();
    String trabajador = txtTrabajador.getText();
    String cliente = txtCliente.getText();

    try {
        PreparedStatement st = con.connect().prepareStatement(sql);
        st.setString(1, marca);
        st.setString(2, costo);
        st.setString(3, trabajador);
        st.setString(4, cliente);

        st.execute();
        System.out.println("Registro guardado exitosamente.");

    } catch(SQLException e) {
        System.out.println("CATCH INSERT!");
        e.printStackTrace();
    } finally {
        con.disconnect();
    }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionActionPerformed
        // TODO add your handling code here
ConnectionManager con = new ConnectionManager();

String Marca_de_Auto = txtMarca_Auto.getText();

// Consulta con TODAS las columnas reales
String sql = "SELECT Marca_de_Auto, Costo_de_Servicio, Nombre_Trabajador, Nombre_Cliente "
           + "FROM configuraciones WHERE Marca_de_Auto = ?";

try {
    PreparedStatement pst = con.connect().prepareStatement(sql);
    pst.setString(1, Marca_de_Auto);

    ResultSet rs = pst.executeQuery();

    if (rs.next()) {

        // LLENADO AUTOMÁTICO DE TODOS LOS TXT
        txtMarca_Auto.setText(rs.getString("Marca_de_Auto"));
        txtServicio.setText(rs.getString("Costo_de_Servicio"));
        txtTrabajador.setText(rs.getString("Nombre_Trabajador"));
        txtCliente.setText(rs.getString("Nombre_Cliente"));
        
        System.out.println("Datos cargados correctamente.");
    } else {
        System.out.println("No existe esa marca en la BD.");
    }

} catch (SQLException e) {
    System.out.println("CATCH!");
    e.printStackTrace();

} finally {
    con.disconnect();
}

    }//GEN-LAST:event_btnSeleccionActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
       ConnectionManager con = new ConnectionManager();
       String sql = "DELETE FROM configuraciones WHERE Marca_de_Auto = ?";
       
       String Marca_de_Auto = txtMarca_Auto.getText();

try {
    PreparedStatement st = con.connect().prepareStatement(sql);
    st.setString(1, Marca_de_Auto);

    int rows = st.executeUpdate(); // ← ESTE MÉTODO DICE CUÁNTAS FILAS BORRÓ

    if(rows > 0){
        System.out.println("Registro eliminado correctamente.");
        JOptionPane.showMessageDialog(null, "Registro eliminado correctamente");

        // OPCIONAL: limpiar campos
        txtMarca_Auto.setText("");
        txtServicio.setText("");
        txtTrabajador.setText("");
        txtCliente.setText("");

    } else {
        JOptionPane.showMessageDialog(null, "No existe esa marca en la base de datos.");
        System.out.println("No existe esa marca.");
    }

} catch(SQLException e){
    System.out.println("CATCH DELETE!");
    e.printStackTrace();
} finally {
    con.disconnect();
}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
       ConnectionManager con = new ConnectionManager();

String sql = "UPDATE configuraciones SET Costo_de_Servicio=?,Nombre_Trabajador=?, Nombre_Cliente=? WHERE Marca_de_Auto=? ;";

String marca = txtMarca_Auto.getText();
String costo = txtServicio.getText();
String trabajador = txtTrabajador.getText();
String cliente = txtCliente.getText();

try {
    PreparedStatement st = con.connect().prepareStatement(sql);

    st.setString(1, costo);
    st.setString(2, trabajador);
    st.setString(3, cliente);
    st.setString(4, marca);   // <-- WHERE

    st.execute();
    System.out.println("Registro actualizado correctamente.");

} catch(SQLException e) {
    System.out.println("ERROR EN UPDATE!");
    e.printStackTrace();
} finally {
    con.disconnect();
}

    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSeleccion;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMarcaAuto;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtMarca_Auto;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTrabajador;
    // End of variables declaration//GEN-END:variables
}
